name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.addon.practice.${project.artifactId}
softdepend:
  - StrikePractice
  - mPractice
  - ProPractice
  - Yang
commands:
  practice-addon:
    aliases: [ispigotpracticeaddon, imanitypracticeaddon, practiceaddon]
