name: iSpigot-PracticeAddon
version: ${project.version}
main: spg.lgdev.addon.practice.iSpigotPracticeAddon
softdepend:
  - StrikePractice
  - mPractice
commands:
  practice-addon:
    permission: ispigot.addon.practice.admin